/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.emagurini.y2021.gestionalestudenti;

public class App {

    public static void main(String[] args) {

        DefaultMenu menu = new DefaultMenu();
        menu.stampa();
    }

}
